
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Image image1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button LaunchButton;
	
	private global::Gtk.Image image2;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Button NewsTitle1;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.Button NewsTitle2;
	
	private global::Gtk.HSeparator hseparator2;
	
	private global::Gtk.Button NewsTitle3;
	
	private global::Gtk.HSeparator hseparator3;
	
	private global::Gtk.Button NewsTitle4;
	
	private global::Gtk.HSeparator hseparator4;
	
	private global::Gtk.Button NewsTitle5;
	
	private global::Gtk.ScrolledWindow scrolledWindow1;
	
	private global::Gtk.TextView MainViewer;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 800;
		this.HeightRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Bassetune Reapers Launcher");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.HeightRequest = 100;
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.WidthRequest = 200;
		this.image1.HeightRequest = 100;
		this.image1.Name = "image1";
		this.image1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, ".\\gameLogo.png"));
		this.hbox1.Add (this.image1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.WidthRequest = 100;
		this.vbox3.Name = "vbox3";
		this.vbox3.Homogeneous = true;
		this.vbox3.Spacing = -10;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.WidthRequest = 150;
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("version 0.000");
		this.vbox3.Add (this.label5);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label5]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Update");
		this.vbox3.Add (this.button3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button3]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.LaunchButton = new global::Gtk.Button ();
		this.LaunchButton.WidthRequest = 200;
		this.LaunchButton.CanFocus = true;
		this.LaunchButton.Name = "LaunchButton";
		this.LaunchButton.UseUnderline = true;
		this.LaunchButton.Label = global::Mono.Unix.Catalog.GetString ("LAUNCH");
		this.hbox1.Add (this.LaunchButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.LaunchButton]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image2 = new global::Gtk.Image ();
		this.image2.WidthRequest = 150;
		this.image2.Name = "image2";
		this.image2.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, ".\\optionsButton.png"));
		this.hbox1.Add (this.image2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image2]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.WidthRequest = 100;
		this.vbox2.Name = "vbox2";
		this.vbox2.Homogeneous = true;
		this.vbox2.Spacing = -40;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.WidthRequest = 100;
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Server Status");
		this.vbox2.Add (this.label4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label4]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Offline");
		this.vbox2.Add (this.label6);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label6]));
		w8.Position = 1;
		w8.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.WidthRequest = 300;
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.WidthRequest = 200;
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.NewsTitle1 = new global::Gtk.Button ();
		this.NewsTitle1.HeightRequest = 80;
		this.NewsTitle1.CanFocus = true;
		this.NewsTitle1.Name = "NewsTitle1";
		this.NewsTitle1.UseUnderline = true;
		this.NewsTitle1.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.NewsTitle1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.NewsTitle1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.NewsTitle2 = new global::Gtk.Button ();
		this.NewsTitle2.HeightRequest = 80;
		this.NewsTitle2.CanFocus = true;
		this.NewsTitle2.Name = "NewsTitle2";
		this.NewsTitle2.UseUnderline = true;
		this.NewsTitle2.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.NewsTitle2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.NewsTitle2]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.Name = "hseparator2";
		this.vbox4.Add (this.hseparator2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator2]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.NewsTitle3 = new global::Gtk.Button ();
		this.NewsTitle3.HeightRequest = 80;
		this.NewsTitle3.CanFocus = true;
		this.NewsTitle3.Name = "NewsTitle3";
		this.NewsTitle3.UseUnderline = true;
		this.NewsTitle3.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.NewsTitle3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.NewsTitle3]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox4.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator3]));
		w16.Position = 5;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.NewsTitle4 = new global::Gtk.Button ();
		this.NewsTitle4.HeightRequest = 80;
		this.NewsTitle4.CanFocus = true;
		this.NewsTitle4.Name = "NewsTitle4";
		this.NewsTitle4.UseUnderline = true;
		this.NewsTitle4.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.NewsTitle4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.NewsTitle4]));
		w17.Position = 6;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.vbox4.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator4]));
		w18.Position = 7;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.NewsTitle5 = new global::Gtk.Button ();
		this.NewsTitle5.HeightRequest = 80;
		this.NewsTitle5.CanFocus = true;
		this.NewsTitle5.Name = "NewsTitle5";
		this.NewsTitle5.UseUnderline = true;
		this.NewsTitle5.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.NewsTitle5);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.NewsTitle5]));
		w19.Position = 8;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.scrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledWindow1.Name = "scrolledWindow1";
		this.scrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.scrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledWindow1.Gtk.Container+ContainerChild
		this.MainViewer = new global::Gtk.TextView ();
		this.MainViewer.WidthRequest = 500;
		this.MainViewer.CanFocus = true;
		this.MainViewer.Name = "MainViewer";
		this.scrolledWindow1.Add (this.MainViewer);
		this.hbox2.Add (this.scrolledWindow1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.scrolledWindow1]));
		w22.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.LaunchButton.Clicked += new global::System.EventHandler (this.OnClick);
		this.NewsTitle1.Clicked += new global::System.EventHandler (this.OnClickNews1);
		this.NewsTitle2.Clicked += new global::System.EventHandler (this.OnClickNews2);
		this.NewsTitle3.Clicked += new global::System.EventHandler (this.OnClickNews3);
		this.NewsTitle4.Clicked += new global::System.EventHandler (this.OnClickNews4);
		this.NewsTitle5.Clicked += new global::System.EventHandler (this.OnClickNews5);
	}
}
